% Compute power spectrum

% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 27-May-2020 12:59:10

% Parameters
timeLimits = [0 2.999979]; % seconds
frequencyLimits = [0 24000]; % Hz

%%
% Index into signal time region of interest
French_U_ROI = French_U(:);
sampleRate = 48000; % Hz
startTime = 0; % seconds
minIdx = ceil(max((timeLimits(1)-startTime)*sampleRate,0))+1;
maxIdx = floor(min((timeLimits(2)-startTime)*sampleRate,length(French_U_ROI)-1))+1;
French_U_ROI = French_U_ROI(minIdx:maxIdx);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[PFrench_U_ROI, FFrench_U_ROI] = pspectrum(French_U_ROI,sampleRate, ...
    'FrequencyLimits',frequencyLimits);
semilogy(FFrench_U_ROI, PFrench_U_ROI)
grid
ax = gca;
ax.FontSize = 18;
xlabel('Frequency (kHz)','FontSize',30)
ylabel('Power Spectrum (dB)','FontSize',30)